version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mjetpax/80sMixtapeAPI
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
      - run: go test -v -cover -coverprofile=/tmp/test.coverprofile -covermode=atomic $(go list ./... | grep -v /vendor/)
      - run: goveralls -coverprofile=/tmp/test.coverprofile -service=circle-ci -repotoken=$COVERALLS_TOKEN
