version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mjetpax/80sMixtapeAPI
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: go test -v -cover -covermode=atomic ./...
